[package]
name = "cripto_api_cryptocurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
